### ISSUE TITLE
`#[proof]` and `#[spec]` syntax for struct fields not recognized

### ISSUE THREAD

**Issue by pratapsingh1729** [verus-lang/verus-analyzer#2]
The `#[proof]` and `#[spec]` syntax for member fields of `struct`s are not recognized by the Verus rust-analyzer. 

Example:

```{rust}
#![allow(unused_imports)]
use builtin::*;
use builtin_macros::*;
mod pervasive;
use pervasive::{*, vec::*, seq::*, option::*, modes::*};

verus!{

pub struct Foo {
    #[proof] pub x: nat
}

}

fn main () {} 
```

results in the following:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/8213281/221268673-bd6ff727-dfc0-49e3-949f-44940c486e87.png">

The error message for `#[proof]` on line 10 is:
`Syntax Error: expected identifier`

**Comment by chanheec** [comment]
ghost/tracked inside struct is now parsed on the current main
