### ISSUE TITLE
Failed to install verus with rust-analyzer in VS code

### ISSUE THREAD

**Issue by tripti-agarwal** [verus-lang/verus-analyzer#24]
[ERROR rust_analyzer::reload] Failed to run proc-macro server from path /Users/name/.rustup/toolchains/1.76.0-aarch64-apple-darwin/libexec/rust-analyzer-proc-macro-srv, error: Custom { kind: Other, error: "proc-macro server's api version (3) is newer than rust-analyzer's (2)" }

**Comment by parno** [comment]
As discussed on Zulip, this is a transient error that doesn't seem to inhibit Verus analyzer from otherwise working, so I'm going to close this for now.

**Comment by parno** [comment]
Closed.
