### ISSUE TITLE
Panic when using "broadcast use"

### ISSUE THREAD

**Issue by panda2134** [verus-lang/verus-analyzer#32]
Shown in the log as "'broadcast use' not implemented yet". Nevertheless, this should not crash Verus-analyzer over and over again and make it unusable.

**Comment by panda2134** [comment]
Introduced by https://github.com/verus-lang/verus-analyzer/commit/21b57b346bf24a637b4cd09e278c39dcf5b943dd#diff-b2a7b219bccc0a9aaf7fa184cdcf356fd773011cb4b2095b11c64ed2a2f9dc63R487. It would be probably better to keep this commit away from the main branch anyway...

**Comment by parno** [comment]
Closed via [4d9dba3](https://github.com/verus-lang/verus-analyzer/commit/4d9dba305616c1c30a66b4d3a09f72d6f48e1ea2)
